[package]
name = "lattice-algebra-rs"
version = "0.1.0"
edition = "2021"
rust-version = "1.70.0"  # Minimum supported Rust version
description = "A Rust library for lattice-based cryptography and algebra"
readme = "README.md"
keywords = ["cryptography", "lattice", "algebra"]
categories = ["cryptography", "algorithms", "math", "science"]

[dependencies]
rand = { version = "0.9.1", features = ["default"] }
rustfft = "6.4.0"
serde = { version = "1.0.216", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.133"
